// Inicio uml
@startuml

// Clase Hotel
class Hotel {
    - nom: String
    - adreça: String
    - habitacions: List<Habitacio> // Se coge la habitacion de la siguiente clase
}

// Clase Habitacio
class Habitacio {
    - numero: int
    - capacitat: int
    - reserva: Reserva
}

// Clase Reserva
class Reserva {
    - dataInici: date
    - dataFi: date
    - client: Client
}

// Clase Client
class Client {
    - nom: String
    - dni: String
}

// Relacion de agregacion "o--"
// El hotel puede tener 0 o mas habitaciones
Hotel "1" o-- "0..*" Habitacio : conté // Texto opcional para describir la relacion

// Relacion de asociacion "-->"
// Una reserva puede estar asociada a maximo una habitacion
Habitacio "0..*" --> "0..1" Reserva : és reservada per


@enduml
// Final uml
