// Inicio uml
@startuml

// Clase Hotel
class Hotel {
    - nom: String
    - adreça: String
    - habitacions: List<Habitacio> // Se coge la habitacion de la siguiente clase
}

// Clase Habitacio
class Habitacio {
    - numero: int
    - capacitat: int
    - reserva: boolean
}

// Clase reserva
class Reserva {
    - dataInici: date
    - dataFi: date
    - client: String
}

@enduml
// Final uml
