// Inicio uml
@startuml

// Solo hay un director, no puedo haber dos iguales
entity Director {
  *id : int 
  *nom : varchar(255)
  *cognom : varchar(255)
}

entity Pelicula {
  *id : int
  *titol : varchar(255)
  *anyEstrena : int
  directorId : int 
}

// Misma relacion que en el ejercicio anterior con autor y libro
Director ||--o{ Pelicula : "dirige"

@enduml
// Final uml
